version: '2'
services:
  node:
    image: node
    container_name: node
    command: bash -c "yarn start"
    restart: always
    working_dir: "/app"
    env_file:
    - producao.env
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
