version: '2'
services:
  node:
    image: node
    container_name: node
    command: bash -c "npm install && npm start"
    restart: always
    working_dir: "/app"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
